services:
  db:
    image: postgres:17.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
